tools:
  java:
    path: /etc/bin/java
  npm:
    path: /etc/bin/npm
  yarn:
    path: /etc/bin/yarn
  maven:
    path: /etc/bin/mvn
  docker:
    path: /etc/bin/docker
  kubectl:
    path: /etc/bin/yarn