gitToolParam:
  java: /usr/bin/git
  credential: GogsCredentials

javaToolParam:
  git: /usr/bin/java

mvnToolParam:
  mvn: /usr/bin/mvn
  setting:
    source: default/conf/maven/setting.xml

npmToolParam:
  npm: /usr/bin/npm
  registry: https://registry.npm.taobao.org

yarnToolParam:
  yarn: /usr/bin/yarn
  registry: https://registry.npm.taobao.org

dockerToolParam:
  docker: /usr/bin/docker
  registry:
    host: 10.72.3.123:80
    credential: HarborCredentials
  templates:
    java:
      dockerignore: default/templates/java/.dockerignore
      dockerfile: default/templates/java/Dockerfile
      kubernetes: default/templates/java/Kubernetes.yml
    node:
      nginx: default/templates/node/nginx.conf
      dockerignore: default/templates/node/.dockerignore
      dockerfile: default/templates/node/Dockerfile
      kubernetes: default/templates/node/Kubernetes.yml

kubectlToolParam:
  kubectl: /usr/bin/kubectl
